# Práctica 4

Utilizar librería NumPy para resolver diferentes situaciones con Arrays y Matrices de Python

* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [1]:
import numpy as np

In [2]:
# A partir de una lista se puede crear un arreglo de NumPy

lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [3]:
#Crear listas rápidamente
arreglo = np.arange(8)
print(arreglo)

[0 1 2 3 4 5 6 7]


In [4]:
#Algunas cosas se pueden hacer con arreglos pero no con  listas:
# 1. Sumarle un mismo elemento

lista + 1

TypeError: can only concatenate list (not "int") to list

In [6]:
arreglo = arreglo + 1

arreglo

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#2. Elevar al cuadrado todos los elementos

lista ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [8]:
arreglo ** 2

array([ 4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
#3. Sumar todos los elementos
print(lista.sum())

AttributeError: 'list' object has no attribute 'sum'

In [12]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [11]:
print(arreglo.sum())

44


In [13]:
#4. Obtener el atributo forma
arreglo.shape

(8,)

In [16]:
arreglo = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6],[1,2,3,4,5,6]])
print(arreglo, '\n', '\n Shape =', arreglo.shape)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] 
 
 Shape = (3, 6)


In [18]:
#5. Transponer los arreglos
arreglo = np.array([[1,2,3,4,5,6]]).T
print(arreglo, '\n', '\n Shape =', arreglo.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] 
 
 Shape = (6, 1)


In [33]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?
print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo, '\n', '* Shape =', arreglo.shape)

print('\n Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]])
print(arreglo.T, '\n', '* Shape =', arreglo.T.shape)

print('\n Arreglo de (2,n)')
arreglo = np.array([[1,2,3],[1,2,3]])
print(arreglo, '\n', '* Shape =', arreglo.shape)

Arreglo de (n,)
[1 2 3 4 5 6] 
 * Shape = (6,)

 Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] 
 * Shape = (6, 1)

 Arreglo de (2,n)
[[1 2 3]
 [1 2 3]] 
 * Shape = (2, 3)


In [37]:
#Transponer no es la unica forma de crear un arreglo de forma (n,1)
arreglo = np.array([[1],[2],[3],[4],[5],[6]])
print(arreglo, '\n', '\n * Shape =', arreglo.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] 
 
 * Shape = (6, 1)


In [40]:
#Multiplicación de arrays
a1 = np.array([[1,2,3,4],[5,6,7,8]])
print(a1.shape)

a2 = np.array([[1,2,3,4],[5,6,7,8]])
print(a2.shape)

a3 = a1 * a2
print(a3.shape)
print('\n',a3)

(2, 4)
(2, 4)
(2, 4)

 [[ 1  4  9 16]
 [25 36 49 64]]


* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [42]:
arreglo = np.arange(start=0, stop= 10, step= 1, dtype= int)
print(arreglo)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
arreglo = np.linspace(start=0, stop=9, num= 100 )
print(arreglo)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask (crea un array o matriz que contiene sólo valores booleanos)

In [45]:
arreglo = np.arange(start=10,stop=101,step=1,dtype=int)
print(arreglo)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [47]:
mascara = ((arreglo % 3)==0)
print(mascara)

[False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False]


In [48]:
arreglo[mascara]

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [49]:
ceros = np.zeros(shape=(5,10))
print(ceros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [50]:
ceros[[1,3],:] = 1
print(ceros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [52]:
ceros[:,[2,7]] = 2
print(ceros)

[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]
